stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:latest  # Docker コンテナで GCC を使用
  services:
    - docker:dind  # Docker in Docker を有効化
  before_script:
    - docker build -t gtest-ci-image -f Dockerfile.ci .
  script:
    - docker run --rm -v $(pwd):/workspace gtest-ci-image /bin/sh -c "
        mkdir -p build && cd build &&
        cmake .. &&
        make"
  artifacts:
    paths:
      - build/
test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run --rm -v $(pwd):/workspace gtest-ci-image /bin/sh -c "
        cd build &&
        ./test/test_mylib"
