stages:
  - build
  - test

build:
  stage: build
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y cmake g++ libgtest-dev
  script:
    - mkdir build && cd build
    - cmake ..
    - make

test:
  stage: test
  script:
    - cd build
    - ./test/test_mylib

